set mouse=v
syn on
colorscheme elflord
set tabstop=4
set shiftwidth=4

" cmap w!! w !sudo tee % >/dev/null
" set fo=tcrq
" set tw=72
map <C-j> {gq}
imap <C-j> <esc>{gq}i


set pastetoggle=<F2>
set t_BE=[200~     " Begin bracketed paste
set t_BD=[201~     " End bracketed paste




" set noanti
" set number

autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif


