#!/bin/sh

# Shortcuts
alias .f="cd $HOME/.dotfiles"
alias .nvim="nvim $HOME/.dotfiles/vim/nvim/init.vim"
alias .alias="nvim $HOME/.dotfiles/system/alias"
alias .path="nvim $HOME/.dotfiles/system/path"
alias .env="nvim $HOME/.dotfiles/system/env"
alias _="sudo"
alias g="git status"
alias e='emacsclient -n'
# alias rr="rm -rf"

if [ -r ~/.dotfiles/bin/nvim ]; then
alias vi='nvim'
alias vim='nvm'
fi

# Global aliases

alias G="| grep -i"
alias H="| head"
alias T="| tail"
alias L="| less"

# Useful aliases

# kill all leftover mosh sessions excluding the current one
alias moshkill="pgrep mosh-server | grep -v $(ps -o ppid --no-headers $$) | xargs kill"

# List declared aliases, functions, paths

alias aliases="alias | sed 's/=.*//'"
alias functions="declare -f | grep '^[a-z].* ()' | sed 's/{$//'"
alias paths='echo -e ${PATH//:/\\n}'

# Directory listing/traversal

LS_COLORS='--color -G'
LS_TIMESTYLEISO='--time-style=long-iso'
LS_GROUPDIRSFIRST='--group-directories-first'

alias l="ls -lahA $LS_COLORS $LS_TIMESTYLEISO $LS_GROUPDIRSFIRST"
alias ll="ls -lA $LS_COLORS"
alias lt="ls -lhAtr $LS_COLORS $LS_TIMESTYLEISO $LS_GROUPDIRSFIRST"
alias ld="ls -ld $LS_COLORS */"
alias lp="stat -c '%a %n' *"

unset LS_COLORS LS_TIMESTYLEISO LS_GROUPDIRSFIRST

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"                  # Go to previous dir with -
alias cd.='cd $(readlink -f .)'    # Go to real dir (i.e. if current dir is linked)

# Network

alias ipl="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias hosts="sudo $EDITOR /etc/hosts"

# Request using GET, POST, etc. method

for METHOD in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$METHOD"="lwp-request -m '$METHOD'"
done
unset METHOD

