#!/bin/sh

username=${1}

echo "Setting up apt packages"
cat << EOF > /etc/apt/apt.conf.d/fucksuggested.conf
APT::Get::Install-Recommends "false";
APT::Get::Install-Suggests "false";
APT::Install-Recommends "false";
APT::Install-Suggests "false";
EOF

apt-get install -y zsh fzf tmux htop iotop suckless-tools vim-nox git tig\
 software-properties-common apt-transport-https jq mosh direnv\
 mtr-tiny nnn apt-file mlocate pwgen silversearcher-ag

# echo "Use doas instead of sudo, permit nopass"
# echo "permit nopass ${username}" > /etc/doas.conf

echo "Starting mlocate and apt-file database updates in background"
(updatedb ; apt-file update) &


