#!/bin/sh

username=${1}

echo "Setting up apt packages"
echo "APT:Install-Recommends \"0\";" | tee > /etc/apt/apt.conf.d/fucksuggested.conf
echo "APT:Install-Suggests \"0\";"  | tee >> /etc/apt/apt.conf.d/fucksuggested.conf

apt-get install -y zsh fzf tmux htop iotop suckless-tools vim-nox git tig\
 software-properties-common apt-transport-https jq\
 mtr-tiny nnn apt-file mlocate pwgen silversearcher-ag

# echo "Use doas instead of sudo, permit nopass"
# echo "permit nopass ${username}" > /etc/doas.conf

echo "Starting mlocate and apt-file database updates in background"
(updatedb ; apt-file update) &


