#!/bin/sh


curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

PROFILE=/dev/null sh /tmp/nvm-install.sh

curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
apt-get update -qy
apt-get install -y nodejs
node -v
